### ISSUE TITLE
footnote parser does not respect rel="lightbox[1]"

### ISSUE THREAD

**Issue by ophian** [textile/php-textile#153]
Example `<a  class="image_link" rel="lightbox[1]" href="example.jpg"><!-- image:2 --><img class="image_left" width="200" height="100"  src=""example.thumb.jpg"  alt="" /></a>`

parses to  ... `rel='lightbox<sup class="footnote"><a href="#fn...">1</a></sup>&#8216;`...

Can we learn textile to not touch these patterns in certain tags? (This was reported with lib v2.4.3. Is it already solved with 3.5.5 or upcoming 3.6?)

**Comment by gocom** [comment]
If there are any instances that would match Textile syntax, but shouldn't be parsed, they can be wrapped in appropriate syntax escaping tags (``==inline==``, ``notextile.``):

    ==<a class="image_link" rel="lightbox[1]" href="example.jpg"><img class="image_left" width="200" height="100" src="example.thumb.jpg" alt="" /></a>==

Will render without it getting formatted.

> Can we learn textile to not touch these patterns in certain tags?

Textile is not aware of its syntaxes' context within the external content-type; the input document is treated as plain-text. Holds true to any other formatting options too (apart quotes).
