### ISSUE TITLE
Typing error on the http://txstyle.org/doc/41/html

### ISSUE THREAD

**Issue by perlhawk** [textile/php-textile#157]
Go to the page: http://txstyle.org/doc/41/html
Find word "notexile".
Please change it to "notextile"

**Comment by netcarver** [comment]
Thank you for the report and sorry for the delay in attending to it. I just visited the page and cannot find the word "notexile" when doing a search in the browser. I believe the site owner may have actioned this already. I'm therefore closing it but please re-open if this is not the case.
