### ISSUE TITLE
Textile input to plaintext output

### ISSUE THREAD

**Issue by ikirudennis** [textile/php-textile#161]
I suspect this issue title sounds ridiculous, but hear me out for a moment...

I use python-textile in a system at my job which sends out emails to clients.  It is sent as an HTML email, but it also includes the plaintext version of the body as well.  So, I created a subclass of textile with a plaintext method which strips any textile-related markup, preserving only the text.  I only have to write the body text once with textile markup, and the HTML and plaintext versions of the email are generated when it is sent.

For example:
```
p{padding:0.5em 0;margin-top:0;}. this is a paragraph with some textile formatting
newlines, "{color: green}a link":http://example.com/
and a date: April 7[^{line-height:0}th^]
```
Would turn into:
```
this is a paragraph with some textile formatting
newlines, "a link":http://example.com/
and a date: April 7th
```

Is there any interest in adding this type of functionality to the official version?

**Comment by netcarver** [comment]
@ikirudennis 

Dennis, whilst I like the idea of being able to target different output doctypes, I think the current implementation  - which munges parse and generation together - probably isn't the best home for a _toPlaintext()_ method. I think you did the right thing using a subclass in this case.

If you are interested, take a look at [Alpaca](https://github.com/netcarver/Alpaca) - a re-write of php-textile that I started about 6 years ago but have no free cycles to take further. It separates the "parser" from the output generators and it includes the beginnings of a plain-text generator.
