### ISSUE TITLE
Method setDocumentType() is no more in v3.5.5 ?

### ISSUE THREAD

**Issue by 7php** [textile/php-textile#162]
Hi, I cannot see the method setDocumentType anymore, has it been superseded or removed?
How is the document_type handle now?

**Comment by 7php** [comment]
I have browsed inside the code, I see it's now injected via constructor
`__construct($doctype = 'xhtml')`

TODO: Update the README to reflect that

**Comment by netcarver** [comment]
7php, thank you for taking the time to submit this. ```setDocumentType()``` is still in [master](https://github.com/textile/php-textile/blob/master/src/Netcarver/Textile/Parser.php#L989) and it allows for post-construction changes to the target document type. This permits re-use an already constructed parsers should anyone wish to re-use them.

**Comment by 7php** [comment]
Oh ok, I see!
It's fine, thanks for the response :)

I think I'll be around as I'm using textile in one of my pet projects as
from this week..

cheers

*-----*

*Kind Regards,- Khayrattee Wasseem*
*{*
*    Twitter  =>  @7php <http://twitter.com/7php> *
*    More..   =>  about.me/khayrattee <http://about.me/khayrattee>*
*};*
