### ISSUE TITLE
Hyphenated class names in tables cells and rows

### ISSUE THREAD

**Issue by ikirudennis** [textile/php-textile#164]
I've noticed a slight bug with how attributes are parsed regarding table cells and rows.  If the cell or row has a class specified which has a hyphen in it, it also adds `vertical-align: middle` to the cell's style attribute.  (The same goes for caret or tilde in the class name, but those seem less likely to used.)  It seems like the vertical-alignment shorthand should only apply when one of those characters is included at the start of the row/cell, otherwise ignored.  Correct?

For example, an old test from python-textile:
```
table(linkblog-thumbnail).
|(linkblog-thumbnail-cell). apple|bear|
```
Using txstyle.org, it turns into:
```
<table class="linkblog-thumbnail">
		<tr>
			<td class="linkblog-thumbnail-cell" style="vertical-align:middle;">apple</td>
			<td>bear</td>
		</tr>
</table>
```

Seems like [this](https://github.com/textile/php-textile/blob/master/src/Netcarver/Textile/Parser.php#L2055) could use a caret at the start.

**Comment by netcarver** [comment]
@ikirudennis Thanks for reporting this Dennis. Now fixed in the [issue-164](https://github.com/textile/php-textile/tree/issue-164) branch and will be merged into master for the next release.

**Comment by netcarver** [comment]
Just pushed the fix for this to master.
