### ISSUE TITLE
Bug with newline in link text

### ISSUE THREAD

**Issue by neffets** [textile/php-textile#167]
1) Try following raw text
<pre>E-Mail: "Line-1
":mailto:test@test.de</pre>

there the newline is ignored and it will lead to Link:
<pre>E-Mail: &lt;a href="mailto:test@test.de"&gt;Line-1&lt;/a&gt;</pre>

2) But it will genrate buggy html if something is written in line two (Branch: origin/3.5, and same on txstyle.org)
<pre>E-Mail: "Line-1
Line-2":mailto:test@test.de</pre>

this will leave a link-prefix "textileRef:..." in the html output
<pre>E-Mail: textileRef:892738635782b165ee7c7:linkStartMarker:“Line-1&lt;br /&gt;
Line-”:mailto:test@test.de</pre>

strange the "2" from Line-2 is lost too.

Branch: origin/3.5

**Comment by neffets** [comment]
Problem is in function **replaceLinks**

There are 2 bugs
* Bug 1: The P-inner does not detect the newlines
    it could be **fixed /xs**  instead of /x

* Bug 2: if it cannot detect correct links.
  It **should remove** the "textileRef:...." at end of processing. All not found links should remove their "textileRef..." at end!

**Comment by netcarver** [comment]
Hello @neffets. Both these defects were fixed some time ago and you should find that the master branch does not exhibit either of these. I note, however, that txstyle.org is still running an old version of textile. I'll look into getting that updated once the latest changes (such as #168) make it into master.

**Comment by neffets** [comment]
see #168 : "issue-168" branch / master have fixed this bug. with "master" a linktext-with-newline works
