### ISSUE TITLE
PHP4 style contstructors are deprecated in PHP7

### ISSUE THREAD

**Issue by richardlampitt** [textile/php-textile#170]
Just received this warning: "Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Textile has a deprecated constructor in /home/vagrant/Code/pack-data/application/libraries/Textile.php on line 206" I figure that as it's not in your issues list that you would like to know of it.

**Comment by netcarver** [comment]
@richardlampitt Which branch are you using?

**Comment by richardlampitt** [comment]
The comments at the top of the Textile.php file are thus: 

`/*
$HeadURL: https://textpattern.googlecode.com/svn/releases/4.2.0/source/textpattern/lib/classTextile.php $
$LastChangedRevision: 2812 $
*/

/*

_____________
T E X T I L E

A Humane Web Text Generator

Version 2.0`

So I guess the version number you're after is either 4.2.0 or 2.0?

**Comment by netcarver** [comment]
@richardlampitt That's a very outdated version of textile (v2.0) as included in a very outdated version of _Textpattern_ (4.2). 

We do have the legacy 2.4 branch of textile in the repo [here](https://github.com/textile/php-textile/tree/2.4) for PHP4 compatibility, but it is deprecated. The other branches (2.5 and 3.5) no longer use the old way of defining constructors.

I think you should consider updating your installation of _Textpattern_ to a more recent version.

Closing this issue.

**Comment by richardlampitt** [comment]
Righteo - thanks for that. I've inherited this project from my new boss, and it comes with no documentation to speak of. I'll add it to my list of things to do!
