### ISSUE TITLE
[SUGGESTION] - Tag current dev-master | Status on Textile

### ISSUE THREAD

**Issue by 7php** [textile/php-textile#171]
Hi @netcarver ,
1) like I saw the last time, the current codebase on master is way ahead of the v3.5.5
In my composer.json I'm using dev-master, but this is risky. Wanted to know if you could tag the current dev-master to maybe v3.5.6 or something?

2) Also, do you have roadmap with php-textile, will you cease dev on it on any future plans? This is by far the best php markup lib made. It would be a waste to see it fade away.

Anything the community can do to help?

Thank you for all you do.

Cheers

**Comment by netcarver** [comment]
Hello @7php,

Thanks for the suggestion and positive feedback. A tagged release is overdue, so thanks for the nudge. However, it will be 3.6.0 not 3.5.6, as there are significant new features in master over the last tagged release. I'll go through the commits and update the changelog. Hopefully you'll have something new next week.

Regarding assistance, we could do with someone willing to work on a site for php-textile.

**Comment by netcarver** [comment]
@7php Done in bac6381. Will add a release and close this issue.

**Comment by netcarver** [comment]
[Done.](https://github.com/textile/php-textile/releases/tag/v3.6.0)

**Comment by 7php** [comment]
hey @netcarver good job mate! You are awesome for your fast response.
Yes 3.6 made more sense than 3.5.6

Regarding:

> Regarding assistance, we could do with someone willing to work on a site for php-textile.

Can you give some more detailed (or bullet-points) of what needs to be done.
