### ISSUE TITLE
Is php-textile PHP 7 compatible 

### ISSUE THREAD

**Issue by dheian** [textile/php-textile#173]
Unless I haven't had enough coffee, I couldn't see if php-textile is 7 compatible. Using an earlier version under 5 but wanted to upgrade.

**Comment by netcarver** [comment]
The travis job that runs the tests runs just fine under PHP 7.0.13 ([link](https://travis-ci.org/textile/php-textile/jobs/176762784)) I haven't yet tested against PHP 7.1.
