### ISSUE TITLE
Getting a registered trademark after an acronym

### ISSUE THREAD

**Issue by dheian** [textile/php-textile#179]
Having a small issue trying to get a registered trademark after an acronym. I'm using the Registered(R) Textile format, but because the word I'm trying to put the mark after is WWE, it's instead treating the (R) as a text tooltip for an acronym. How do I handle this?

**Comment by eliph** [comment]
==WWE==(R)

**Comment by netcarver** [comment]
@dheian Try something like this...

    Here is a well known acronym: WWW(World Wide Web)[_(r)_].

**Comment by dheian** [comment]
Sorry for the late reply. I'll give this a try. 

On September 28, 2017 4:48:10 AM EDT, Steve <notifications@github.com> wrote:
>@dheian Try something like this...
>
>    Here is a well known acronym: WWW(World Wide Web)[_(r)_]. 
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/textile/php-textile/issues/179#issuecomment-332771436

-- 
Ian Evans
Executive Producer
DigitalHit.com
(typed on a smartphone with dumb thumbs so please excuse spelling misturks.)
