### ISSUE TITLE
CSS attrib in PHP7: small code fix

### ISSUE THREAD

**Issue by kieranmathieson** [textile/php-textile#181]
Thanks for the parser! Useful thing.

PHP7 is a bit stricter about using array syntax for strings. Gives an error in Parser.php on 2063:

`$style[] = rtrim($sty[1], ';');`

Fix is to change line 2032 from...

`$style = '';`

...to...

`$style = [];`

**Comment by netcarver** [comment]
Thanks for the report Kieran. This was actually fixed in commit 579c4d56 last year.
