### ISSUE TITLE
request: Hardrule (hr. --> <hr>)

### ISSUE THREAD

**Issue by wion** [textile/php-textile#183]
A request made a few times over the years in the Txp forum. Granted it's not a huge advantage over the regular HTML anyway, but it seems like `hr.` and `hr(class).` is an easy win here.

Netcarver had mentioned a knock up of one in Textplugs (#7 ). Don't know if Textplugs is still a viable thing anymore. If not, could close that issue and #151 .

cc @Bloke, @bloatware

**Comment by wion** [comment]
Ah... looking at this, maybe you need something after the dot? That's why it's not so easy? I overlooked that. You know me, none dev here. Reject as seen fit.

**Comment by bloatware** [comment]
FWIW, `<hr />` at the beginning of a line will not be textiled in the latest txp.

**Comment by gocom** [comment]
> FWIW, `<hr />` at the beginning of a line will not be textiled in the latest txp.

Neither does it in PHP-Textile. It is one of the many spec fixtures.

**Comment by wion** [comment]
Closing, because I really don't mind using HTML for the `hr` element anyway. Same for `q` element. It's little syntax either way and dead clear in the HTML format anyway.
