### ISSUE TITLE
links at ends of endnote-related sentences

### ISSUE THREAD

**Issue by wion** [textile/php-textile#185]
### Expected behaviour

When making an endnote number immediately following a link, for example:

```
. . . "link text":url.[#firstnote] Start of next sentence . . .
```

I would expect the output to be (where '1' is a superscript)...

> . . . [link text](#).[1](#) Start of next sentence . . .

### Actual behaviour

Instead the terminal punctuation and expected note number disappear:

> . . . [link text](#) Start of next sentence . . .

#### Additional information

A similar problem happens in the endnote itself. In these cases I have a pattern for using annotation comments (author comments) after sources, for example:

```
notelist(endnotes):‡.

note#firstnote. First Last, 'Title of article', Source Name, DD MMM YYYY, URL %(class)Annotation text here.%
```

The `class` provides a hook to style the comment as desired, with block display under the source info and surrounded with straight brackets via pseudo elements to indicate it's an author comment. For the most part this works great and outputs like:

>1. First Last, 'Title of article', Source Name, DD MMM YYYY, URL
>
>  [Annotation text here.]

But if the comment terminates with a link (i.e. `. . ."here":url.%`), similar to the first problem, it outputs like this, with a broken span and no terminal `.]` ...

> %(class)Annotation text [here](#)

I can avoid both problems, of course, by avoiding links in those two situations, and I do.

But it does seem like a bug, and as I tried to describe in the forum, [here](https://forum.textpattern.io/viewtopic.php?id=49013), probably not clearly, I can't seem to use any Textile escape workaround on those links either, probably because of conflicts between two sets of straight brackets in that case.

Just pointing it out.

**Comment by gocom** [comment]
> making an endnote number immediately following a link

The problem with this is knowing where the link should end and what should be considered as part of the URL. Slicing, and overall parsing URLs, is rather error-prone especially when it comes to the note/fn reference syntax.

In cases where note references, or other markup, directly follows links, the alternative, more Markdown-like format can be used:

```
["Roses":https://example.com][#red]
```

Same also works for spans and other inline markup:

```
%["red":https://examle.com].%
```

**Comment by philwareham** [comment]
Sure, if you can open issues at the website repo itself and list and new features I’ll roll that in. I have a snagging list of fixes to do on that website anyway so I’ll do at same time.
