### ISSUE TITLE
Remove references to Dean's email address

### ISSUE THREAD

**Issue by petecooper** [textile/php-textile#187]
There are two instances of Dean Cameron's email address (`<dean@textism.com>`) that I've found so far, and these should probably be removed. The `textism.com` domain dropped, was reregistered in 2016 and has since been transferred to another party, and it now diverts to a travel-related website.

Dean died in January 2018 and I'm sure the current owner of the domain is not connected to Dean or his family in any fashion. With that in mind, I propose to leave Dean's name and credits as-is, but remove the email address.

**Comment by philwareham** [comment]
Thanks, this is done now via your PR. Closing.
