### ISSUE TITLE
notextile

### ISSUE THREAD

**Issue by colak** [textile/php-textile#191]
### Prerequisites

* [ ] Are you running the latest version of PHP-Textile?
* [ ] `$ composer update`?

### Problematic Textile markup

```
something<notextile><txp::short-tag /></notextile>
```

### Expected output

```html
something<sup class="tooltip"><a href="#fn1" id="foot1">1</a><span class="tooltiptext noprint">footnote</span></sup>
```

### Actual output

The `<notextile />` tag is not recognised when not preceded by a space, as identified on [forum.textpattern.io/viewtopic.php?pid=317977#p317977](https://forum.textpattern.io/viewtopic.php?pid=317977#p317977)

### Used PHP code

```php
{Please write here}
```

#### Additional information

PHP-Textile version: the one shiping with txp 4.7.3
PHP version: 7.2.18

**Comment by gocom** [comment]
Square bracket syntax can now be used to get the expected output:

```
foo[==<bar>==]
```

Produces:

```
<p>foo<bar></p>
```

P.S. I recommend using `==` instead of `<notextile>` that isn't very Textile-like syntax; it is just some legacy syntax that has stuck around.
