### ISSUE TITLE
Remove hard-coded styling on <tfoot>

### ISSUE THREAD

**Issue by wion** [textile/php-textile#196]
### Is your feature request related to a problem?

Not a functional problem, but certainly a presentational one.

### What is the feature?

I'm wondering why the `<tfoot>` (more specifically, the `<td>...</td>` inside the table footer) has hard-coded styling on it, this:

```
style="padding-left:1em; padding-right:1em; text-align:center;"
```

I never want center-aligned footer text there, and I'd also prefer having control over padding, but I seem to have no control over either.

If you look at a lot of slick table usage in printed texts, white papers, reports, science articles, and so on, you'll often see headings or data items notated with reference marks (*, †, ‡, §, ¶, ‖ . . .) when they need special attention. The notes themselves are added in the table footers, respectively:

```
* First note
† Second note
‡ Third
§ etc
```

This is how and what I use table footers for, and this particular marks system is common in guidelines (e.g. _New Oxford Style Manual_, p 311, 333). But the centre alignment of text isn't compatible.

Any chance we can neuter this so users can style their `tfoot` as they please?

**Comment by wion** [comment]
I haven't really looked at the other anatomical parts of the table to see if there's similar gremlins, but it might be prudent to make the who table sterile, if other such presentation encoding exists.

**Comment by wion** [comment]
Just realized I can override it with another local style, for example:

```
|~.
|\5={text-align:left;}. * Note here... |
|-.
```
But considering how unwieldy Textile tables are already, it seems not having to override styles with more styles is the wiser direction?

**Comment by gocom** [comment]
PHP-Textile does not add styling to tables, or other items it generates. You have text-alignment set because of the center alignment attribute,  `=` (which is present in your example), and padding likely due to padding attributes `)` and `(`.

The following:

```
|~.
|. Footer |
```

Generates:

```
<table>
	<tfoot>
		<tr>
			<td>footer</td>
		</tr>
	</tfoot>
</table>
```

**Comment by wion** [comment]
Thanks. I thought it was weird that any styling would be added. I completely overlooked the Textile table notation for alignment and padding. It is a bit abstract, after all. ;)
