### ISSUE TITLE
Closing double quote

### ISSUE THREAD

**Issue by cara-tm** [textile/php-textile#197]
### Prerequisites

* [✔ ] Are you running the latest version of PHP-Textile?
* [ ] `$ composer update`?

### Expected behaviour

I noticed Textile adds a non-breaking space `&nbsp;` before the closing french double quote sign.
It is good in order to avoid widow effect. But the opening one hasn't such a non-breaking space. Maybe you could project to adopt one of these two solutions:
*  adding a non-breaking space after the opening quote;
* change for a better (recommanded by typographic rules) HTML entity: `&#8239;` (after the opening and before the closing quote).

### Steps to reproduce

Write an article with the French as the Textpattern interface language and use double quotes `"` surrounding a word (they will be converted after saving).

#### Additional information

PHP-Textile version: 3.7.3
PHP version: 7.1.5 (MAMP PC)

**Comment by gocom** [comment]
This appears to be related to Textpattern CMS and the quote conversion, and localisation providing/configuring it does. PHP-Textile itself does not do localised quotes with non-breaking spaces.

**Comment by bloatware** [comment]
Yep, `txp_quote_double_open` string in `fr.ini` needs to be modified.

**Comment by cara-tm** [comment]
Thank you lot.
