### ISSUE TITLE
Extra space after em

### ISSUE THREAD

**Issue by cara-tm** [textile/php-textile#210]
### Prerequisites

* [x] Are you running the latest version of PHP-Textile?
* [ ] `$ composer update`?

### Problematic Textile markup

```
Textile (current version) seems to add a space after <em> rendering HTML tag. Try:
_word_,
```

### Expected output

```html
<em>word</em>,
```

### Actual output

```html
<em>word</em> ,
```

### Used PHP code

```php
{Please write here}
```

#### Additional information

PHP-Textile version: latest
PHP version: 7.4

**Comment by gocom** [comment]
I can not produce this directly. Input:

```
word,
```

Generates HTML:

```
<p><em>word</em>,</p>
```

**Comment by cara-tm** [comment]
You're right. Sorry...
Closed.
