### ISSUE TITLE
'Passing null to parameter' error under PHP 8.1.0

### ISSUE THREAD

**Issue by Bloke** [textile/php-textile#215]
### Prerequisites

* [x] Are you running the latest version of PHP-Textile?
* [ ] `$ composer update`?

### Expected behaviour

No errors under PHP 8.1.0 (alpha)

### Actual behaviour

Error: Passing null to parameter #3 in preg_split()

### Steps to reproduce

Run Textpattern in debugging mode and save a Textile-enabled article.

[Line 3256](https://github.com/textile/php-textile/blob/master/src/Netcarver/Textile/Parser.php#L3256) needs -1 as its third param instead of null. All the other instances of `preg_split()` are fine.

**Comment by gocom** [comment]
Release 3.7.7 fixes these.

https://github.com/textile/php-textile/releases/tag/v3.7.7
