### ISSUE TITLE
Disabling block tags parsing also disables hyperlinks

### ISSUE THREAD

**Issue by bloatware** [textile/php-textile#225]
### Prerequisites

* [x] Are you running the latest version of PHP-Textile?
* [ ] `$ composer update`?

### Expected behaviour

`setBlockTags(false)->parse('"Link":https://example.com')` outputs `<a href="https://example.com">Link</a>`.

### Actual behaviour

Hyperlinks are not processed.

#### Additional information

PHP-Textile version: 4.1.0
PHP version: any

See [here](https://github.com/textpattern/textpattern/issues/1925) for a background.

I guess `links()` function is never called in this mode. Adding it before `glyphs()` on l.1976 seems to fix the problem (if any).

**Comment by gocom** [comment]
@bloatware Thank you for reporting this.

**Comment by gocom** [comment]
Release v4.1.1 contains fix for this issue:
https://github.com/textile/php-textile/releases/tag/v4.1.1

**Comment by bloatware** [comment]
Thank you for the prompt fix.
