### ISSUE TITLE
Package class file (Parser.php) as included external library in GPLv2 project?

### ISSUE THREAD

**Issue by sjnorton-aa** [textile/php-textile#226]
Hi, I've volunteered to port a contrib module from Drupal CMS v7 to Backdrop CMS. The module adds the ability to parse Textile markup to content creation forms in the CMSs. The module depends on the Textile class library to do the processing, but in the past users were asked to extract the (then) classTextile.php library from the Textpattern tarballs. (The original Drupal project is here: https://www.drupal.org/project/textile) 

I was wondering if, in addition to pointing users to the GitHub repository (rather than Textpattern), it would be acceptable (or wise) to include the current latest version of Parser.php, along with its readme and license files, in the module package. Both the original Drupal module and any Backdrop module must be licensed under GPLv2, and the the Textile parser's BSD 3-clause license is considered compatible with GPLv2.

This is my first try at porting a module, and I'm doing it because I have a lot of older content on the site I'm migrating to Backdrop that uses Textile markup - which I'd rather not have to find and edit. I thought others might be in a similar situation.

I would welcome any advice or feedback about this effort. Thanks in advance!

**Comment by gocom** [comment]
We in general would recommend including/installing PHP-Textile library in your module project using [Composer](https://getcomposer.org/) dependency manager.

> I was wondering if, [...] it would be acceptable (or wise) to include the current latest version of Parser.php, along with its readme and license files, in the module package

You are free to do so license-wise; we have nothing against that 🙂

Altho, from techinical point-of-view, keep in mind that the project does use multiple class-files and is intended to be used with PSR-4 autoloader (which is made simpler with Composer). While you can manually include the files in the project, note that in the future more classes can be added to the library, which then you have to manually load in your project too.

**Comment by sjnorton-aa** [comment]
@gocom thank you for your response. Under the circumstances, it would still make more sense to bundle the 3 class files with the Backdrop module.

On the one hand, guidance for contrib developers urges bundling external libraries under most circumstances ([see discussion here](https://docs.backdropcms.org/documentation/using-libraries)). On the other hand, many folks who shifted from Drupal to Backdrop (including me) did so because the heavy reliance on Composer in D8+ made maintaining small projects prohibitively complex. So requiring Composer for just my module would be counter to the larger project philosophy. I'll just have to maintain it manually.

I would be happy to include other information and attributions (beyond the normal) about your project if there is something more you'd like put in there. I was first drawn to Textile many years ago, and I'm glad to see it's being actively maintained.
