### ISSUE TITLE
PHP 8.4: Implicitly marking parameter as nullable is deprecated

### ISSUE THREAD

**Issue by bloatware** [textile/php-textile#227]
PHP 8.4 is not released yet, but just in case:

https://github.com/textile/php-textile/blob/2aa23a5b6ff57780616ac2fcea220a62d0cf1052/src/Netcarver/Textile/DataBag.php#L67
https://github.com/textile/php-textile/blob/2aa23a5b6ff57780616ac2fcea220a62d0cf1052/src/Netcarver/Textile/Tag.php#L86

Possibly elsewhere

**Comment by gocom** [comment]
Thanks for raising this issue, @bloatware 🙂

Resolving this will require dropping PHP 5 support, or either removing types from arguments. Will likely just drop PHP 5 support, and release it as next major release version.

**Comment by gocom** [comment]
Release [v4.1.2](https://github.com/textile/php-textile/releases/tag/v4.1.2) is now available, and is compatible with PHP 8.4.
