### ISSUE TITLE
Security vulnerability responsible disclosure

### ISSUE THREAD

**Issue by CERT-PL-CNA** [textile/php-textile#228]
Hello,

a security vulnerability in this repository has been found and reported to CERT.PL. How can we send the details privately? 
We don't see any security policy describing how such vulnerabilities should be reported.

**Comment by gocom** [comment]
I've now added [security policy](https://github.com/textile/php-textile/blob/master/SECURITY.md) to the repository, and opened GitHub's private security advisatory reporting, which one may use to report vulnerabilties to us 🙂
