### ISSUE TITLE
Add support for HTML5 elements

### ISSUE THREAD

**Issue by netcarver** [textile/php-textile#9]
HTML5 will introduce multiple new elements that textile doesn't yet support.

**Comment by wion** [comment]
Depending on how 'generic' the ideas proposed in this thread are meant to be for php Textile versus, say, how it's used specifically in Textpattern, maybe this issue could be closed now?

In Textpattern, for example, using elements like `figure` and `aside` are done quite handily now via Textpattern [shortcodes](https://docs.textpattern.com/tags/shortcodes/custom-short-tags-and-shortcodes). Here are examples for [figures](https://docs.textpattern.com/tags/shortcodes/image-with-caption-shortcode) and [asides](https://docs.textpattern.com/tags/shortcodes/aside-quote-shortcode). 

Regardless, maybe it's better to just open a new issue for a given element if/when it needs discussed?

cc @Bloke, @bloatware

**Comment by bloatware** [comment]
Adding a tag is easy, but the markup for tags inside it is not evident. For example, `aside` often contains `p` and other block-level tags. Nothing of the following would currently work:
```
aside. p.

aside..
p.
```
Suggestions welcome.

**Comment by bloatware** [comment]
@philwareham good point, Textile is for writing texts, not creating templates.
