### ISSUE TITLE
Allow indication of language for code blocks (esp. inline)

### ISSUE THREAD

**Issue by netcarver** [textile/php-textile#96]
It would be useful to allow some kind of language markup on  code blocks to better support syntax highlighting.

`bc.` and `bc..` already support class, id, style and language attributes but inline code `@...@` has no support for any of these. In addition, the [W3 spec](http://www.w3.org/html/wg/drafts/html/master/text-level-semantics.html#the-code-element) suggest the use of classes named after the programming language but prefixed with "language-" be used on the `<code>` elements.

Currently typing...

```
bc(php). echo ...
```

...into textile would lead to...

```
<pre class="php"><code>echo...
```

...which doesn't follow this suggestion.  In keeping with textile's aim of trying to reduce keystrokes, perhaps we need a new convention for 'language tagging' of code blocks.

Should we override the use of the existing language attribute marker for code blocks or do something different again? Ideas anyone?

**Comment by philwareham** [comment]
It would be really handy to revise this issue and allow for classnames to be applied to the inner `code` tag. Basically using Textile with a highlighter such as Prism is not possible right now.

Don't hardcode it to use any predefined `language-*` prefix either - let the user decide this.

So, as an example, using:

    bc(line-numbers)[language-markup]. some code

Would render:

    <pre class="line-numbers"><code class="language-markup">some code</code></pre>

**Comment by netcarver** [comment]
@philwareham Just pushed a test branch that has this feature in it. Please try out the [issue-96 branch](https://github.com/textile/php-textile/tree/issue-96) and let me know if it does what you need.

**Comment by philwareham** [comment]
@netcarver works great for me, thanks!

**Comment by netcarver** [comment]
@philwareham Thanks for testing. Do you anticipate any call for this on inline code elements?

**Comment by philwareham** [comment]
I guess it's always good to have the option available for inline too, if it's not too much trouble to implement.

**Comment by netcarver** [comment]
Looking at the source for handling the inline code spans - I'm inclined to leave it to a later version unless there is demand for it.

**Comment by philwareham** [comment]
No worries. It's edge case stuff really.

**Comment by netcarver** [comment]
I've added the "Breaks backwards compatibility" label as this change will cause a small variation in the generated output if anyone happens to be using the language attributes on a block code element.
